// Generated by CoffeeScript 1.12.4
(function() {
  var randomStyle, setStyle;

  $.getJSON('css/style.json', function(result) {
    return setStyle(randomStyle(result.styles));
  });

  randomStyle = function(styles) {
    var currentStyle;
    currentStyle = styles[Math.floor(Math.random() * styles.length)];
    return currentStyle;
  };

  setStyle = function(style) {
    $('head').append('<link id="page-style" rel="stylesheet/less" href="css/' + style + '.less"/>');
    less.sheets.push($('#page-style')[0]);
    return less.refresh();
  };

}).call(this);
