// Generated by CoffeeScript 1.12.4
(function() {
  var styleList;

  styleList = {};

  $.getJSON('css/style.json', function(result) {
    console.log(result);
    return styleList = result;
  });

  console.log(styleList);

}).call(this);
